---
- assert:
    that:
      - icinga2_server_ticket_salt
    fail_msg: "required 'icinga2_server_ticket_salt' must be a random string"
    success_msg: "required 'icinga2_server_ticket_salt' is set"

- set_fact:
    icinga2_constants:
      TicketSalt: "{{ icinga2_server_ticket_salt }}"
      ZoneName: main
      NodeName: "{{ icinga2_server_nodename | default(ansible_fqdn) }}"
    icinga2_confd: false
    icinga2_features:
      - name: "{{ icinga2_server_ido_type }}"
        host: "{{ icinga2_server_ido_host }}"
        port: "{{ icinga2_server_ido_port }}"
        user: "{{ icinga2_server_ido_user }}"
        database: "{{ icinga2_server_ido_database }}"
        password: "{{ icinga2_server_ido_password }}"
      - name: checker
      - name: notification
      - name: mainlog
      - name: api
        ca_host: none
        force_newcert: false
        endpoints:
          - name: NodeName
        zones:
          - name: ZoneName
            endpoints:
              - NodeName
- set_fact:
    icinga2_features: "{{ icinga2_features + icinga2_server_features }}"
  when: icinga2_server_features is defined

- import_role:
    name: icinga.icinga.repos
  when: icinga2_server_manage_repos

- import_role:
    name: icinga.icinga.icinga2
