---
- set_fact:
    icinga2_features: "{{ icinga2_features + icinga2_server_features }}"
  when: icinga2_server_features is defined

- import_role:
    name: icinga.icinga.repos
  when: icinga2_server_manage_repos

- import_role:
    name: icinga.icinga.icinga2
