---
- name: List of unique files found in icinga2_monitoring_objects
  set_fact:
    _object_files: "{{ icinga2_monitoring_objects | map(attribute='file') | unique | list }}"

- name: remove tmp directory
  file:
    state: absent
    path: "{{ icinga2_tmp_config }}"

- name: create tmp directories
  file:
    state: directory
    path: "{{ icinga2_tmp_config }}/{{ item }}"
  loop: "{{ _object_files }}"

- name: generate configuration objects
  template:
    dest: "{{ icinga2_tmp_config }}/{{ item.file }}/{{ item.order|default('000') }}_{{ item.object_type }}_{{ item.object_name }}"
    src: "objects_template.j2"
  loop: "{{ icinga2_monitoring_objects }}"

- name: ensure monitoring directories
  file:
    state: directory
    dest: "{{ icinga2_config_location }}/{{ item | dirname }}"
  loop: "{{ _object_files }}"

- name: assemble monitoring configuration files
  assemble:
    dest: "{{ icinga2_config_location }}/{{ item }}"
    src: "{{ icinga2_tmp_config }}/{{ item }}"
  loop: "{{ _object_files }}"
  register: _assemble

- name: find all actual config files
  command: "{{ icinga2_find_bin }} {{ icinga2_config_location }} -name '*.conf' -printf '%P\n'"
  register: _all_object_files

- name: purge monitoring files
  file:
    state: absent
    path: "{{ icinga2_config_location }}/{{ item }}"
  loop: "{{ _all_object_files.stdout_lines | difference(_object_files) }}"
  register: _purge

- name: validate icinga2 config
  command: icinga2 daemon -C
  notify: reload icinga2 service
  when: _assemble.changed or _purge.changed
