---

- name: collect all config objects for myself
  set_fact:
    tmp_objects: "{{ tmp_objects| default([]) + hostvars[item]['icinga2_objects'][ansible_fqdn] }}"
  with_items: "{{ groups['all'] }}"
  when: hostvars[item]['icinga2_objects'][ansible_fqdn] is defined

- icinga2_object:
    args: "{{ item }}"
  with_items: "{{ tmp_objects }}"
  when: tmp_objects is defined
  register: result

- set_fact:
    icinga2_local_objects: "{{ icinga2_local_objects|default([]) + [item.dest] }}"
  with_items: "{{ result.results }}"
  when: result.results is defined
